### ISSUE TITLE
Scout Alarm switches off when triggered

### ISSUE THREAD

**Issue by Tom2527** [jordanryanmoore/homebridge-scout#41]
**Describe the bug**
When the alarm is armed (in Away or Night mode), and a door/window is opened, triggering an Access Sensor, the security system switches to OFF in HomeKit

**To Reproduce**
1. Arm the Scout Alarm (to Away or Night)
2. Trigger an Access Sensor by opening a door or window
3. Immediately the Security System in HomeKit switches to OFF
4. ScoutAlarm continues with a countdown (which I configured) and after that the siren activated. There's no notification in HomeKit about the triggered alarm.

**Expected behavior**
I'm not sure what the expected behaviour would be as I never had a security system in HomeKit, but I assume the alarm stays armed and a notification is sent out stating the alarm is triggered.
Note that while HomeKit claims the alarm is switched to OFF, it's still armed as the sirene goes off (after the countdown).

**Screenshots**

**Logs**
If applicable, include any relevant portions of Homebridge logs.

**Additional context**

**Comment by jordanryanmoore** [comment]
Thanks for the bug report!

Last time I tested this on my own system, the behavior in the Home app was that the armed mode (Stay/Away/Night) stayed the same, but it showed the status system as “Triggered”.

Unfortunately, this will likely be difficult to root cause without significantly more information about your Scout system, particularly while it’s alarming. I’ll take some time this week to push out a new release with more verbose logging.

For now, I do have a few follow-up questions:

1. What version of iOS or macOS are you viewing the Home app on?

2. What version of iOS or tvOS is your HomeKit hub running (if any)?

**Comment by Tom2527** [comment]
Thanks for the support. 
I’m on the latest public versions of iOS and tvOS (13.3). 

I just tried if maybe the issue is related to the countdown/alarm delay option that confuses HomeKit but that’s not the case. The issue still exists without the delay. 

I do assume the logic of triggering the alarm remains in the Scout app? There does not seem to be any logic in the Home app to configure when to trigger.

**Comment by jordanryanmoore** [comment]
This is how the Home app displays a Security System when it's in the triggered state:

<img width="113" alt="Screen Shot 2019-12-30 at 7 52 00 AM" src="https://user-images.githubusercontent.com/112001/71590947-53c95b00-2adf-11ea-992f-6b8ab33c679a.png">

<img width="301" alt="Screen Shot 2019-12-30 at 7 52 08 AM" src="https://user-images.githubusercontent.com/112001/71590955-5a57d280-2adf-11ea-8a06-22f15000a00d.png">

Of note, if you're looking at the detailed view of an accessory (the second screenshot above), the Home app doesn't seem to update the state for any change unless you close and open it.

**Comment by jordanryanmoore** [comment]
I've pushed a new version (0.2.2) of the plug-in to NPM that adds more logging. Would you be willing to update the plug-in, test again, and post the Homebridge logs here?

If you're not comfortable posting the logs publicly here, feel free to message me on the [homebridge community slack](https://homebridge-slackin.glitch.me/).

**Comment by Tom2527** [comment]
Hi, version 0.2.2 crashes for me.

[12/30/2019, 9:17:03 PM] Loaded plugin: homebridge-scout
Dec 30 21:17:03 raspberrypi homebridge[3374]: internal/fs/utils.js:220
Dec 30 21:17:03 raspberrypi homebridge[3374]:     throw err;
Dec 30 21:17:03 raspberrypi homebridge[3374]:     ^
Dec 30 21:17:03 raspberrypi homebridge[3374]: Error: ENOENT: no such file or directory, open './package.json'
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Object.openSync (fs.js:440:3)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Object.readFileSync (fs.js:342:35)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-scout/index.js:9:39)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:171:14)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Array.forEach (<anonymous>)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Module._compile (internal/modules/cjs/loader.js:959:30)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
Dec 30 21:17:03 raspberrypi homebridge[3374]:     at Module.load (internal/modules/cjs/loader.js:815:32)
Dec 30 21:17:03 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE


I managed to fix this issue by running npm init to create a package.json file. Then I moved on to run homebridge as a service with systemctl. But this gives the following (similar?) error.

Dec 30 21:19:23 raspberrypi homebridge[3697]: [12/30/2019, 9:19:23 PM] Loaded plugin: homebridge-scout
Dec 30 21:19:23 raspberrypi homebridge[3697]: internal/fs/utils.js:220
Dec 30 21:19:23 raspberrypi homebridge[3697]:     throw err;
Dec 30 21:19:23 raspberrypi homebridge[3697]:     ^
Dec 30 21:19:23 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE

Any suggestions?

**Comment by Tom2527** [comment]
I did however manage to test version 0.2.2 for the triggering issue. Turns out that if I wait a while, the alarm does go off, and the correct state is eventually reflected in HomeKit. However, in between the triggering of the alarm and the alarm actually sounding, HomeKit reports the alarm as OFF.

**step 1) Arming Away Mode in HomeKit:** 
[12/30/2019, 9:37:17 PM] [ScoutAlarm] Mode [54ca4d86671a81ce96000033] arming event fired.

**step 2) Away mode actually armed.** Notice this takes almost a minute. No idea why:
[12/30/2019, 9:38:03 PM] [ScoutAlarm] Mode [54ca4d86671a81ce96000033] armed event fired.

**step 3) Trigger the alarm**Here, I triggered the door panel. In HomeKit the alarm immediately switches to OFF. In Scout the alarm stays armed.
[12/30/2019, 9:38:50 PM] [ScoutAlarm] Device [0a70080064100452584da000a0000100] triggered event fired.
[12/30/2019, 9:38:50 PM] [ScoutAlarm] Mode [54ca4d86671a81ce96000033] triggered event fired.
[12/30/2019, 9:39:06 PM] [ScoutAlarm] Device [0a70080064100452584da000a0000100] triggered event fired.

**step 4) Alarm sounds** After 45s the sirene does go off, and in HomeKit the status changes to "triggered". I'm not sure why it takes 45s as I disabled the alarm delay in Scout. HomeKit does not send out a notification about this.
[12/30/2019, 9:39:35 PM] [ScoutAlarm] Mode [54ca4d86671a81ce96000033] alarmed event fired.

**step 5) Dismiss alarm**I dismiss the alarm in Scout
[12/30/2019, 9:39:48 PM] [ScoutAlarm] Mode [54ca4d86671a81ce96000033] dismissed event fired.

**Comment by jordanryanmoore** [comment]
Ok, first of all, I pushed a new version (0.2.3) that should fix the crash in 0.2.2… 🤦‍♂️

For step 2, the delay between `arming` and `armed` is so you can set your system to away and leave your house (open a door) before the alarm mode is set and would trigger an alarm. This is entirely controlled by Scout and is working as expected.

Thanks to your testing (and the new logging), I can see what the actual problem is though. The mode state transitions as follows:

`disarmed` ➡ `arming` ➡ `armed` ➡ `triggered` ➡ `alarmed` ➡ `dismissed`

The problem is that I'm not currently accounting for the `triggered` state. Unfortunately, there's not a direct mapping of these mode states to HomeKit security system states. A HomeKit security system can only be one of the following:

* `STAY_ARM`
* `AWAY_ARM`
* `NIGHT_ARM`
* `DISARMED`
* `TRIGGERED`

When the mode state is `alarmed`, the HomeKit state should obviously be `TRIGGERED`, but I feel like it's less clear if the mode state is `triggered` that the HomeKit state should shift to `TRIGGERED` or stay in its current armed state since Scout is only counting down a grace period.

I'm leaning towards the latter (maintaining state until the actual alarm), and it probably warrants a user-configurable option, but it needs a sane default.

Thoughts?

**Comment by Tom2527** [comment]
thanks for the quick reply. I think the "triggered" state should map to the current armed state. The alarm is not sounding yet, so HomeKit should remain "unaware". 
I'm not even sure if it warrants a user-configurable option as the grace period typically allows the user to dismiss the alarm before sounding. So if you would allow the user to map it to triggered, HomeKit would assume the alarm is sounding, which is not the case.

**Comment by Tom2527** [comment]
version 0.2.3 does indeed fix the crash. Great. 
One thing though: the "security system tile" is now grouped together with one of my contact sensors. Assuming this is not something that changed in the plugin code, I assume HomeKit does not like accessories to magically come and go as a result of homebridge changes so it probably got things mixed up. And I'll get it fixed when I re-add homebridge to HomeKit.

**Comment by jordanryanmoore** [comment]
I've pushed a fix and included it in a new release (0.2.4).

Thanks again for your help!

**Comment by Tom2527** [comment]
I have updated to version 0.2.4 but the issue is not yet fixed for me. Alarm switches to OFF when triggering.

**Comment by jordanryanmoore** [comment]
Hmm… I was able to repro the bug in 0.2.3, but confirmed it was fixed with 0.2.4.

Can you upload a new set of your Homebridge logs and a screenshot of your Scout mode configuration?

**Comment by jordanryanmoore** [comment]
Actually, can you update to 0.2.5 and run `homebridge --debug` to capture logs? It will include a bunch of additional data about your Scout configuration.

**Comment by Tom2527** [comment]
I just tried this scenario again and it works perfectly now. I'm 100% sure I was on 0.2.4 and restarted homebridge before. Anyway, you can close this report. Sorry for the confusion and thanks for the great work!

**Comment by Tom2527** [comment]
I noticed this issue again when the system was armed in a state not mapped to a HomeKit state. I have a state called Vacation and when that one triggers the alarm, the issue raised its head again. I did not test this yet with version 0.6.1 though.

**Comment by jordanryanmoore** [comment]
First, a little background:

* The available HomeKit security system modes are fixed (stay, away, night, off). There is no way to alter them, like by adding a vacation mode. This is a limitation of HomeKit.
* When a HomeKit security system is armed or triggered, it's a specific mode that is armed or triggered (not the system itself). There is no way to generically to tell HomeKit that the system is armed or triggered without specifying that it is the stay, away, or night mode that is in that state.

Thus, if you have a Scout mode that isn't mapped to a HomeKit security system mode, there's no way for HomeKit to indicate that mode is armed or triggered. Unfortunately, I don't see much that I can do here within the constraints of a HomeKit security system. The only thing I can offer is that the present solution provided in #55 would be able to create switches for every Scout mode, not just the limited HomeKit set.

**Comment by Tom2527** [comment]
I understand, but I assume this is linked to issue #56. If the plugin configuration would allow to map multiple states to one HomeKit state, the issue would be fixed.

**Comment by jordanryanmoore** [comment]
Let's continue the conversation on #56, since it's not actually related to the original issue here.
